### PR TITLE
Apply as grid ufunc axis arg

### PR DESCRIPTION
**Pull request by TomNicholas**
Expands upon #362 by adding an `axis` argument to `apply_as_grid_ufunc`. 

That argument should have been part of #362, but nobody noticed - instead what has been happening without this PR is that the axis to operate over is read verbatim from the signature, so the only reason the tests passes was because my signatures used the same letters (`"X"` & `"Y"`) to denote the dummy indices as are used for the real axis names in the test data! :facepalm: The test fixtures in `test_grid_ufunc.py` have now had their Axes renamed to avoid this happening again.

(Only https://github.com/xgcm/xgcm/pull/371/commits/e2b18d16a07bafd13b956242304f0cffe5438516 onwards are new commits here - I still don't really get where all this extra git history comes from)

 - [x] Tests added
 - [x] Passes `pre-commit run --all-files`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by TomNicholas** [comment]
This seems work, except that the one test I added to test applying a grid ufunc over one axis of a 2D array fails, and I don't know whether I'm just being silly but I can't really work out why (`TestGridUFunc.test_apply_along_one_axis`):

```
E       AssertionError: Left and right DataArray objects are not equal
E       
E       Differing values:
E       L
E           array([[ -3,  -5,  -7,  -9, -11, -13, -15, -17,  77],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  75],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  73],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  71],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  69],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  67],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  65],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  63],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17, 160]])
E       R
E           array([[ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80],
E                  [ -3,  -5,  -7,  -9, -11, -13, -15, -17,  80]])

xgcm/test/test_grid_ufunc.py:317: AssertionError
```

**Comment by jbusecke** [comment]
I am not seeing the test function you mention. Am I missing something? Can you plot the output of `grid.pad` for debugging? This smells like weird boundary conditions?

**Comment by TomNicholas** [comment]
> I am not seeing the test function you mention.

That's because I forgot to push that last commit

**Comment by TomNicholas** [comment]
> I don't know whether I'm just being silly but I can't really work out why

I was being silly the test function needed an `axis` kwarg to work as intended. 

The test failures are expected from the code that was merged in from the "main" project branch. Merging this now as it is relied upon by later PRs.

**Pull request merged**
