### PR TITLE
Support for Exchange between Faces

### LINKED ISSUE #76: cubed-sphere exchanges
Many models (e.g. MITgcm, GEOS, GFDL FV3) use "tiles" or "faces" of locally orthogonal curvilinear grids which are connected at the tile faces.

MITgcm cubed sphere grid

In xmitgcm, for example, each face is a dimension: variables have dimensions of `('time', 'k', 'face', 'j', 'i')`. For xgcm to difference and and interpolate correctly on such models, it needs a way to exchange data across the tile faces.

I have created a prototype for doing these exchanges via an xarray decorator in this gist:
https://gist.github.com/rabernat/6c18194ec55ca46b0139f33a9a9f805a

It would not be super hard to add this functionality to xgcm. (Special logic would be needed for vectors.) This would enable xgcm to work "out of the box" on such datasets.

cc @jetesdal, @maikejulie, @darothen

### PR DESCRIPTION
**Pull request by rabernat**
- [x] Fixes #76 
- [x] Comprehensive tests
- [x] Documentation

This is a first draft at modifying xgcm's guts to allow for more complex grid geometries, such as the MITgcm LLC grids, cubed-sphere grids, etc.

cc @maikejulie, @jetesdal

### CODE REVIEW

**Comment by rabernat** [comment]
Just updating @maikejulie and @jetesdal that my latest commit (85cb3e2) enables the ability to interpolate and difference 2D c-grid vectors (e.g. u and v) from cell edges to cell centers. This is what you need in order to do the volume and tracer budgets.

What does not yet work is interpolating / differencing such vectors to the cell edges, such as for calculating vorticity. For various technical reasons, that turns out to be much more difficult.

The testing is pretty bare bones. And I definitely need to add more documentation. I am going to write a bit more documentation and then merge this, hopefully within a few days. I want to get this into your hands so I can get your feedback about the API and help finding bugs.

I just wanted to provide some evidence that I am, as promised, continuing to work on this (instead of sleeping).

**Comment by jbusecke** [comment]
Should I wait for fixing the grid generation stuff, until the interpolation works? I am asking since that is an essential part of what my module uses.

**Comment by rabernat** [comment]
@jbusecke I don't understand your question.

**Comment by jbusecke** [comment]
My bad, I did not read carefully. I will take a look at it in the next days and see if I can get the grid generation to work.

**Comment by maikejulie** [comment]
Hey Ryan and Julius,

Sounds great, and I'm very glad we're discussing this! Having something
work for tracer and volume budgets is a great start.

I'll provide more feedback and help in the next few weeks. I'd be super
excited to have this work for vorticity budgets!

Thanks,
Maike

**Comment by rabernat** [comment]
The vorticity budgets will be super hard. This is due to the topology of the llc grid. Probably easier to discuss in person at ocean sciences.

**Comment by maikejulie** [comment]
Definitely better in person. Scribbles are semi-essential.

Being able to compute the curl, streamfuctions etc are things that come up
regularly talking about the needs of the llc/ecco users, so I rate this as
important beyond just my own curiosity.

We should discuss.

Maike

**Comment by rabernat** [comment]
Just to clarify where we are at, you can do all of those things *now* with xgcm, just excluding the points on the face edges.

**Comment by maikejulie** [comment]
Jepp. I know. Thanks!

Global maps are pretty great though!

Particularly, the streamfunction on a face is not as exciting as the global
picture!

**Comment by rabernat** [comment]
Despite the broken tests (related to grid autogeneration), I would like to merge this PR in order to keep things moving forward. In particular, I know that @maikejulie and @ifenty are eager to try it out with the ECCOv4 tutorials. I will fix the autogeneration stuff in a future PR.

Would anyone like to provide a review before I  merge?

**Pull request merged**
