### PR TITLE
Joss paper

### PR DESCRIPTION
**Pull request by rabernat**
We should submit a paper about xgcm to Journal of Open Source Software
- [Submission instructions](https://joss.readthedocs.io/en/latest/submitting.html)
- [Review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html)

Some todos:
- [x] update authorship to reflect full list of xgcm [contributors](https://github.com/xgcm/xgcm/graphs/contributors)
- [x] proofread and refine paper.md
- [x] include more examples of usage in publications if they exist
- [ ] check license for pycomodo figure to make sure we can reuse it
- [ ] maybe make a nice eye candy figure
- [ ] figure out how to use this [ruby script](https://gist.github.com/arfon/478b2ed49e11f984d6fb) to generate paper metadata

I would like to offer authorship on this to everyone who has contributed:
```
$ git shortlog -s -n
   151  Ryan Abernathey
    26  Timothy Smith
    17  Julius Busecke
     4  stickler-ci
     3  jbusecke
     3  Anderson Banihirwe
     1  Nick Swanson-Hysell
     1  Raphael Dussin
     1  Stickler Bot
     1  Willi Rath
     1  timothys-sverdrup
     1  Anirban Sinha
     1  Christopher L.P. Wolfe
     1  Ci Zhang
     1  Dhruv Balwada
     1  Leonardo Uieda
```

so that means @timothyas, @andersy005, @Swanson-Hysell,  @raphaeldussin,  @willirath, @anirban89, @geosciz, @pittwolfe, @dhruvbalwada, @leouieda. 

If you would like to be an author, please make a PR to my branch with your authorship information.

### CODE REVIEW

**Comment by Swanson-Hysell** [comment]
While the offer is appreciated, my single commit was a minor typo correction so no need for me to be author. Best wishes for your work on this paper.

**Comment by dhruvbalwada** [comment]
I am not sure what I contributed either, probably was just some minor typo as well. So would like to bow out as well, thanks for the offer.

**Comment by timothyas** [comment]
This is not a publication, but xgcm does provide the backbone for a lot of the analysis routines within [ECCOv4-py](https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Example_MHT.html#), e.g. computing MHT on an LLC grid. That could be worth mentioning, especially since the LLC grid generally gives people a headache but xgcm handles interpolation, differencing pretty nicely. I could add a paragraph and/or a figure via a PR if you like.

**Comment by leouieda** [comment]
Thank you for the invitation! I also just submitted a typo fix so no need for authorship. Maybe for the 2.0 publication when I've made some larger contributions :wink: Let me know if you want any tips or clarifications for the JOSS process/paper.

**Comment by rabernat** [comment]
> I could add a paragraph and/or a figure via a PR if you like.

Yes @timothyas - would love it if you could add a few sentences about this in the applications section.

**Comment by jbusecke** [comment]
I dug out some pictures that I made a while ago from our idealized tracer experiments. Both show the absolute surface gradient calculated with xgcm. Unfortunately they both have no colormap, not sure if this should be a purely visual representation. Then these could work nicely.
Visualisation_ScienceArt-JBusecke
Gradient_global

**Comment by rabernat** [comment]
I think this is more-or-less ready to go. However, JOSS has [suspended submissions](https://joss.theoj.org/papers/new) for now. So we will have to put it on hold

**Comment by jbusecke** [comment]
Seems like they are [open again](https://twitter.com/JOSS_TheOJ/status/1300385228238860289?s=20). What do we need for this to be submitted?

**Comment by rabernat** [comment]
Thanks for the reminder Julius. I will start the submission process asap.

**Comment by rabernat** [comment]
I decided against the eye-candy figure. It's very large and I don't want to add it to the repo. Plus I just want to get this done.

**Comment by rabernat** [comment]
I submitted the paper to JOSS for review! Thanks for the push @jbusecke.

**Comment by jbusecke** [comment]
Awesome! I am already loving my first day!

**Comment by rabernat** [comment]
https://github.com/openjournals/joss-reviews/issues/2628

**Comment by rabernat** [comment]
And now here:

https://github.com/openjournals/joss-reviews/issues/2631

**Pull request merged**
