### PR TITLE
Pin docrep < 0.3.0

### PR DESCRIPTION
**Pull request by jbusecke**
Band aid towards #210

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for working oh this @jbusecke! 

Looks like you need this also in the doc env. RTD build is failing.

**Comment by jbusecke** [comment]
Thanks @rabernat, I am encountering a few issues in this 'simple fix'

- The [Travis Build](https://travis-ci.org/github/xgcm/xgcm/builds/723093371) is failing due to black formatting issues and I am not sure why that is...

-  I dont see the travis status in the "checks" section below. Its a nuisance, but still bothers me.

Ill see what I can do here and report back.

**Comment by jbusecke** [comment]
> I dont see the travis status in the "checks" section below. Its a nuisance, but still bothers me.

I think we are still testing on *.org*, which should probably be fixed. we could also think about migrating to circleci or github actions?

**Comment by rabernat** [comment]
Yes, we really need to fix our testing infrastructure. Forget travis. Github Actions FTW! Let's discuss this in a new issue (which I will open).

**Comment by jbusecke** [comment]
> The Travis Build is failing due to black formatting issues and I am not sure why that is...

I think it is the new major version of black, which probably has some different formatting. I am still using a 19.xx version and somehow my local conda is a complete mess and wont install anything. I guess its time for a full wipe as part of the onboarding haha.

**Comment by jbusecke** [comment]
I switched black to the conda dependencies (which does not have the latest version yet and added the docrep pin to the docs ci environment). Seems to work now. 

I would open a seperate docrep issue and make sure to remind us to take these out once we refactor?

**Comment by jbusecke** [comment]
Turns out I already had an issue open 😁 (#207). 

**The testing situation rn is very dangerous actually**. It just showed me 'all tests passed' while the travis build failed...def need to fix this quickly and before starting any other work.

**Comment by jbusecke** [comment]
@rabernat could you double check the status [here](https://travis-ci.org/github/xgcm/xgcm/builds/723117557) and confirm that the tests were successful? Then we can merge this and Ill hop over to work on #213.

**Comment by jbusecke** [comment]
This will be superseeded by #214, so I think Ill shut it down.

**Pull request closed without merging**
