### PR TITLE
Add Python 3.9

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds support for Python 3.9

 - [ ] ~~Closes #xxxx~~
 - [ ] Tests added
 - [x] Passes `pre-commit run --all-files`
 - [ ] ~~User visible changes (including notable bug fixes) are documented in `whats-new.rst`~~
 - [ ] ~~New functions/methods are listed in `api.rst`~~

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Note the failing `upstream` CI build is fixed over in https://github.com/xgcm/xgcm/pull/320

**Review by jbusecke — APPROVED** [review]
This looks good to me @jrbourbeau. I retriggered the CI, just for completeness. After that this can be merged in my view.

**Comment by jbusecke** [comment]
Ah sorry I am stupid, the rerunning does not help. Ill merge anyways.

**Comment by jrbourbeau** [comment]
No worries, I just merged the current development branch into this PR which should result in all green checks here

**Pull request merged**
