### PR TITLE
Get ready to release 0.5.1

### LINKED ISSUE #277: Patch release after #263
Perhaps a new minor patch release after #263? v0.5.1?

### PR DESCRIPTION
**Pull request by jbusecke**
- [ ] Closes #277 
 - [ ] Passes `black . `

### CODE REVIEW

**Comment by jbusecke** [comment]
There seems to be an issue with the CI. Ill wait for a bit and try again. cc @navidcy

**Comment by jbusecke** [comment]
Hmm it is not a problem with the CI, but it seems like we cant satisfy the newest requirements of upstream numba:
```
Pip subprocess error:
439
ERROR: Could not find a version that satisfies the requirement llvmlite<0.36,>=0.35.0.dev0 (from numba==0.52.0rc1->-r /home/runner/work/xgcm/xgcm/ci/condaenv.w00zvcd3.requirements.txt (line 9)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0rc1, 0.33.0, 0.34.0rc1, 0.34.0)
440
ERROR: No matching distribution found for llvmlite<0.36,>=0.35.0.dev0 (from numba==0.52.0rc1->-r /home/runner/work/xgcm/xgcm/ci/condaenv.w00zvcd3.requirements.txt (line 9))
```

I would be inclined to ignore for now and see if this problem persists?

**Comment by jbusecke** [comment]
I think as long as all the main CI jobs are successful, we can bump this issue to the next minor release?
@rabernat is that ok with you?

**Comment by rabernat** [comment]
🚀 amazing! Thanks Julius!

What is our release procedure these days?

**Comment by jbusecke** [comment]
Just tag the version and gh actions do the rest!

**Comment by jbusecke** [comment]
I added a little instruction how to release in #279. I am thinking of keeping that away from the docs for now? Just a little reminder for folks, so that xgcm can still be released if I am away!

**Comment by navidcy** [comment]
does this https://anaconda.org/conda-forge/xgcm gets updated automatically?

**Pull request merged**
