### PR TITLE
Derivative docs

### LINKED ISSUE #160: Typo in metric docs
Just found
> It is now possible to integrate over e.g. the X axis with:

This should be `Z` instead.

Will fix that in an upcoming PR. 

But seeing this, I think it would be very helpful to have some way to build RTD for PRs.

### PR DESCRIPTION
**Pull request by timothyas**
This adds to doc/grid_metrics.ipynb to show example usage of `.derivative`

Additionally,
- I reworded some other stuff in this notebook to fix #160 
- I changed the format of the "Notes" to [this style](https://nbsphinx.readthedocs.io/en/latest/markdown-cells.html#Info/Warning-Boxes) so they look nice :) 
- I made a note that the `.derivative` performs centered differencing not a finite volume differencing scheme. However, I think I know how this can be done, I could just foresee some issues when 'time' gets added as a grid axis (and perhaps other issues too). If you're interested I could do some more testing on an initial branch I've started and open a PR, or I could try to contribute to something else in the long [to do list](https://github.com/xgcm/xgcm/projects/1) before next week, and save this for later.

### CODE REVIEW

**Comment by jbusecke** [comment]
👏 👏 👏 Thank you so much for getting this done so quick @timothyas ! These look great.

I think in the long run we should have a better example dataset (where you dont have to interpolate metrics/data; even though it is good to show how to do that!). 

I think it might help showing the derivative with depth as a function of depth (at least once), e.g. a profile of e.g. u and du/dz plotted on top of that? What do you think? You can leave the map to give global context.

> I changed the format of the "Notes" to this style so they look nice :)

Very cool. How did you do that in the notebook? I am writing up the docs for all the shiny new functions (weighted mean, cumulative integral, conservative (weighted) interpolation) and this might come in handy. 

> I made a note that the .derivative performs centered differencing not a finite volume differencing scheme. However, I think I know how this can be done, I could just foresee some issues when 'time' gets added as a grid axis (and perhaps other issues too). If you're interested I could do some more testing on an initial branch I've started and open a PR, or I could try to contribute to something else in the long to do list before next week, and save this for later.

Good point. I am currently dealing with a similar issue for interp in #162, and opted to add an option `conservative=...`. I could imagine implementing an option like that into `derivative`. If I understand correctly the finite difference version of `grid.derivative(da, 'Y')` would just be `grid.diff(da*dx, 'Y') / area_xy`? Or is there any case where a model does `grid.diff(da*dx*dz, 'Y') / volume_xyz`? We could even implement those as options `conservative='horizontal'`/ `conservative='volume'` or something along those lines.

Are you coming to the hackathon btw? My priorities are to get the new features in #162 ready and then document them properly. I would very greatly appreciate it if you could test and review over there. But obviously tackling any of the other ones would be awesome too! 

Again a huge thanks for getting involved in xgcm!

**Comment by jbusecke** [comment]
>Very cool. How did you do that in the notebook? I am writing up the docs for all the shiny new functions (weighted mean, cumulative integral, conservative (weighted) interpolation) and this might come in handy.

Sorry it is right there in the link... 🤦‍♂

**Comment by timothyas** [comment]
Hey @jbusecke, thanks for the feedback! Yeah I agree a vertical profile would help for intuition. I included a side by side plot in the latest commit using those handy integrate functions to get a horizontal average :)

> Good point. I am currently dealing with a similar issue for interp in #162, and opted to add an option `conservative=...`. I could imagine implementing an option like that into `derivative`. If I understand correctly the finite difference version of `grid.derivative(da, 'Y')` would just be `grid.diff(da*dx, 'Y') / area_xy`? Or is there any case where a model does `grid.diff(da*dx*dz, 'Y') / volume_xyz`? We could even implement those as options `conservative='horizontal'`/ `conservative='volume'` or something along those lines.

Yeah nice! I think this would be a good way to implement FV conservative derivatives. I think to perform a finite volume derivative, the formula will always be grid.diff( da * area , axis) / volume. Then xgcm can figure out whether those are 1,2, or 3D based on the underlying metrics/coordinates. If we were to additionally add a 'horizontal' derivative form it's not totally clear to me what that would correspond to in the case of >2D but maybe I'm not picturing something right. I would foresee options like "centered-finite-difference" (i.e. what's implemented now) or "conservative", but like I said maybe I'm missing where 'horizontal' would be used. 

> Are you coming to the hackathon btw? My priorities are to get the new features in #162 ready and then document them properly. I would very greatly appreciate it if you could test and review over there. But obviously tackling any of the other ones would be awesome too!

Nope I'm not joining, I actually didn't know about it until I saw your to-do list, but I'm just happy to help contribute where I can since you guys have a deadline coming up. I think xgcm is super useful and want it to get the attention it deserves! I'll try some testing when I can, and see where I can contribute without creating a "too-many-cooks-in-the-kitchen" effect...

**Comment by jbusecke** [comment]
> handy integrate functions to get a horizontal average :)

Gets even handier in #162 😁 

> grid.diff( da * area , axis) / volume 

area here is in the x-z or y-z plane right? I think I have a good idea to implement this soon. But for now we have made a great step forward! 

> but I'm just happy to help contribute where I can since you guys have a deadline coming up. I think xgcm is super useful and want it to get the attention it deserves! I'll try some testing when I can, and see where I can contribute without creating a "too-many-cooks-in-the-kitchen" effect...

Its not a hard deadline, but I truly appreciate all your help. No such thing as 'too-many-cooks-in-the-kitchen' as long as all changes are discussed and agreed upon! 

Regarding this PR I am unsure how well I will be able to rebase onto #162, which also has changed docs in the notebook? Do you have experience in merging those? @rabernat, what do you think is best in this case?

**Comment by timothyas** [comment]
I don't have experience merging notebooks. I have this notebook on two different machines though, so I could do it the "manual" way once #162 is merged

**Comment by jbusecke** [comment]
Thats awesome. I would like to prioritize #162,  because it adds functionality.


Julius J.M. Busecke, Ph.D. (he/him)
———————————————
Postdoctoral Research Associate
Princeton University • Geosciences
408A Guyot Hall • Princeton NJ
jbusecke.github.io<http://jbusecke.github.io>

On Oct 15, 2019, at 9:50 AM, Timothy Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't have experience merging notebooks. I have this notebook on two different machines though, so I could do it the "manual" way once #162<https://github.com/xgcm/xgcm/pull/162> is merged

**Comment by timothyas** [comment]
Hey @jbusecke: with some light googling I found [nbdime](https://nbdime.readthedocs.io/en/latest/) which made rebasing this to master not bad at all - pretty cool! 

Anyway, with the latest commit I added the equations showing the continuous version of the operations we're computing, as well as the underlying xgcm routines that go on "under the hood" for the specific example. I'd be happy to add some documentation for metric weighted interpolation, should I do that here or in a separate PR?

**Comment by jbusecke** [comment]
If you could include it that would be phenomenal!

**Comment by timothyas** [comment]
Hey @jbusecke, this latest commit has a quick example for using metric weighted interp. As you mentioned in the other PR the example with the current dataset is fairly limited (I didn't see that note until I realized I needed to wrap my head around what was going on with the weighted interp..). So this addition doesn't exactly provide an "advertisement" for using metric weighted interpolation, but at least provides example usage. Let me know what you think! Good luck preparing for tomorrow.

**Comment by jbusecke** [comment]
Awesome! I will fetch the branch once I arrive at Columbia and take a quick look. Expect to merge it quickly.

I might repeating myself but your help has been very helpful in getting xgcm ready for this event. Sincere thanks.


Julius J.M. Busecke, Ph.D. (he/him)

———————————————

Postdoctoral Research Associate

Princeton University • Geosciences

408A Guyot Hall • Princeton NJ

juliusbusecke.com

On Oct 15, 2019, at 10:52 PM, Timothy Smith <notifications@github.com> wrote:

﻿

Hey @jbusecke<https://github.com/jbusecke>, this latest commit has a quick example for using metric weighted interp. As you mentioned in the other PR the example with the current dataset is fairly limited (I didn't see that note until I realized I needed to wrap my head around what was going on with the weighted interp..). So this addition doesn't exactly provide an "advertisement" for using metric weighted interpolation, but at least provides example usage. Let me know what you think! Good luck preparing for tomorrow.

**Comment by jbusecke** [comment]
These are beautiful! Just got a chance to look at them. Thanks again.

**Comment by timothyas** [comment]
That’s great to hear @jbusecke! I’m glad it was helpful and I hope the hackathon was awesome. I definitely enjoyed the tweets 🙂

**Pull request merged**
