### PR TITLE
Jbusecke/autogenerate docs

### PR DESCRIPTION
**Pull request by jbusecke**
Here is a more extensive documentation of the autogenerate module.

This addresses #77 and #86.

Is there a better way to link from a notebook to the API section of the documentation? When I render it locally it looks quite ugly with the full link.
screen shot 2018-06-29 at 12 28 22 pm

This is the code in my notebook:

```
The [`autogenerate`](http://xgcm.readthedocs.io/en/latest/api.html#module-xgcm.autogenerate) module
```

@rabernat, with regards to #86, I think the latest improvements of the automatic padding (e.g. extrapolation) implemented in #96 make the default settings much more useful. Could you give it a test run perhaps?

### CODE REVIEW

**Comment by willirath** [comment]
> Is there a better way to link from a notebook to the API section of the documentation? When I render it locally it looks quite ugly with the full link.

Looks fine for me on a local Jupyterlab, Jupyter-Notebook and also on Github.

**Comment by jbusecke** [comment]
Oh another thing: I added a dataset for my global example. I guess we would want to avoid bloating the repo with netcdf files. I was not able to find a global example in the xarray tutorial datasets. Should we follow the same strategy as xarray in the long-term, and outsource the actual data files?

**Comment by rabernat** [comment]
> Is there a better way to link from a notebook to the API section of the documentation?

I found this page in the nbsphinx docs:
https://nbsphinx.readthedocs.io/en/0.3.4/markdown-cells.html#Links-to-Domain-Objects
It explains how to use autodoc links within the notebook. Is that what you have done? In any case, that's what I recommend.

> I guess we would want to avoid bloating the repo with netcdf files. I was not able to find a global example in the xarray tutorial datasets. Should we follow the same strategy as xarray in the long-term, and outsource the actual data files?

This is a very good point. I'm not sure the best way to solve it though. I once recall finding a package that managed the test datasets automatically. But I can't track it down now. Let's not let that hold things up.

Overall, I really like you example and think it will make a great addition to the docs!

Once you have decided you are happy with the linking issue, I will merge this.

**Comment by jbusecke** [comment]
Ook. I removed the old autogenerate docs, fixed some typos and implemented the API links.

**Pull request merged**
