### PR TITLE
Metric aware ufuncs

### PR DESCRIPTION
**Pull request by TomNicholas**
Makes `metric_weighted` kwarg work for new grid_ufunc refactor. Builds on #380

 - [ ] Closes #xxxx
 - [ ] Tests added
 - [ ] Passes `pre-commit run --all-files`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by TomNicholas** [comment]
Still need to ensure that code always consults the `Axis` objects to see if kwarg defaults are already defined, e.g. `fill_value` can be set on `Axis` (during `Grid.init`) or overriden when `Grid.diff` is called.

**Comment by TomNicholas** [comment]
This doesn't quite work and I'm not sure why - I get assertion errors saying some of the test results are not close:

```
========================================================================================== FAILURES ==========================================================================================
__________________________________________________________________________ test_boundary_global_input[10-fill-diff] __________________________________________________________________________

funcname = 'diff', boundary = 'fill', fill_value = 10

    @pytest.mark.parametrize(
        "funcname",
        [
            "interp",
            "diff",
            "min",
            "max",
            "cumsum",
            "derivative",
            "cumint",
        ],
    )
    @pytest.mark.parametrize("boundary", ["fill", "extend"])
    @pytest.mark.parametrize("fill_value", [0, 10, 5.0, None])
    def test_boundary_global_input(funcname, boundary, fill_value):
        """Test that globally defined boundary values result in
        the same output as when the parameters are defined on either
        the grid or axis methods
        """
        ds, coords, metrics = datasets_grid_metric("C")
        axis = "X"
    
        # Test results by globally specifying fill value/boundary on grid object
        grid_global = Grid(
            ds,
            coords=coords,
            metrics=metrics,
            periodic=False,
            boundary=boundary,
            fill_value=fill_value,
        )
        func_global = getattr(grid_global, funcname)
        global_result = func_global(ds.tracer, axis)
    
        # Test results by manually specifying fill value/boundary on grid method
        grid_manual = Grid(
            ds, coords=coords, metrics=metrics, periodic=False, boundary=boundary
        )
        func_manual = getattr(grid_manual, funcname)
        manual_result = func_manual(
            ds.tracer, axis, boundary=boundary, fill_value=fill_value
        )
>       xr.testing.assert_allclose(global_result, manual_result)
E       AssertionError: Left and right DataArray objects are not close
E       
E       Differing values:
E       L
E           array([[[[ 0.092988, ...,  0.262704],
E                    ...,
E                    [-0.700335, ...,  0.773538]],
E           
E                   ...,
E           
E                   [[ 0.359261, ...,  0.272375],
E                    ...,
E                    [ 0.35324 , ...,  0.291507]]],
E           
E           
E                  ...,
E           
E           
E                  [[[-0.963276, ..., -0.319598],
E                    ...,
E                    [-0.991009, ..., -0.225018]],
E           
E                   ...,
E           
E                   [[-0.794481, ..., -0.031931],
E                    ...,
E                    [-0.833957, ..., -0.332291]]]])
E       R
E           array([[[[ 0.092988, ...,  0.262704],
E                    ...,
E                    [-0.700335, ...,  0.773538]],
E           
E                   ...,
E           
E                   [[ 0.359261, ...,  0.272375],
E                    ...,
E                    [ 0.35324 , ...,  0.291507]]],
E           
E           
E                  ...,
E           
E           
E                  [[[ 9.036724, ...,  9.680402],
E                    ...,
E                    [ 9.008991, ...,  9.774982]],
E           
E                   ...,
E           
E                   [[ 9.205519, ...,  9.968069],
E                    ...,
E                    [ 9.166043, ...,  9.667709]]]])

xgcm/test/test_metrics_ops.py:123: AssertionError

```

**Comment by jbusecke** [comment]
Wait, when did this happen? After refactoring?

**Comment by TomNicholas** [comment]
Yes I think this was the case at the end of our hack the other day...

**Comment by TomNicholas** [comment]
commit aa6271d is potentially dodgy (@jbusecke) - it was what we were working on when we kept getting those non-repeatable failures ...

**Comment by jbusecke** [comment]
Should we close this in favor of #407?

**Comment by jbusecke** [comment]
Closed in favor of #407

**Pull request closed without merging**
