### PR TITLE
Fix typo and url rendering in Contributor's Guide

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by jbusecke** [comment]
Oh thanks for catching these @navidcy. The RTD [build is broken](https://readthedocs.org/projects/xgcm/builds/24068874/), but as far as I can tell this is unrelated to the changes you made. I think we were seeing the same issue in #627. Let me investigate this and get back to this PR.

**Comment by navidcy** [comment]
Seems you need sphinx v5?

**Comment by navidcy** [comment]
@jbusecke I merged master and docs build seem fine now.

**Comment by jbusecke** [comment]
Sorry for the delay here @navidcy, and thanks for the fix.

**Pull request merged**
