### PR TITLE
Migrate example notebooks to xgcm-examples

### LINKED ISSUE #258: Put examples into a standalone repo / integrate with pangeo gallery
Our list of examples is growing, and there are new proposals for examples / tutorials coming in (see #216, #257)

I would propose that we put the examples into a new repo (e.g. `xgcm-examples`) and use [pangeo gallery](http://gallery.pangeo.io/contributing.html) / [binderbot](https://github.com/pangeo-gallery/binderbot) to automatically build them in the cloud. Then we could use a git submodule in xgcm to make the built notebooks appear as part of the docs.

What do you think?

### PR DESCRIPTION
**Pull request by jbusecke**
Here I have started to migrate most of the example notebooks out to [xgcm-examples](https://github.com/xgcm/xgcm-examples) and then added them back to the documentation using git submodules.

 - [x] Closes #258
 - [x] Passes `black . `

### CODE REVIEW

**Comment by rabernat** [comment]
Fantastic work Julius! And it works on RTD?

**Comment by jbusecke** [comment]
The PR did, yes!

**Comment by jbusecke** [comment]
Hmmm but the master build failed https://readthedocs.org/projects/xgcm/builds/12706019/. 
Weird. Is there a way to retrigger the build on RTD?

**Comment by jbusecke** [comment]
Seems like it was some hickup on the RTD side. Looks good now: http://xgcm.readthedocs.org/

**Pull request merged**
