### PR TITLE
Fix broken sphinx build

### PR DESCRIPTION
**Pull request by jbusecke**
Summary: This pins a buch of packages to deal with an issue that broke backwards compatibility for sphinx<5 (more info here: https://github.com/readthedocs/readthedocs.org/issues/11140). I also moved all of the dependencies for the doce into `doc/environment.yaml` to avoid confusion/duplication vs dependencies defined in `setup.py`.
 - [x] Passes `pre-commit run --all-files`
 - [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by navidcy** [comment]
Do you need to add the compat requiremet here:

https://github.com/xgcm/xgcm/blob/2bafd2abbdd3a81165a42a95b9bfad444a9ad9f4/setup.py#L16

?

**Comment by jbusecke** [comment]
Ok I think I found what is going on:
From [here](https://readthedocs.org/projects/xgcm/builds/24071198/)
image
It seems they just inject another `-sphinx` to the environment file 🙈.

**Comment by jbusecke** [comment]
Ok I am getting some releavant gh issues: https://github.com/readthedocs/readthedocs.org/issues/11140 with a suggested workaround [here](https://github.com/dask/dask-sphinx-theme/issues/68#issuecomment-1893198477). Going to give that a spin...

**Comment by jbusecke** [comment]
Nice this worked. Ill merge this now..

**Pull request merged**
