### PR TITLE
Added whats-new section in docs

### PR DESCRIPTION
**Pull request by jbusecke**
I added a `whats-new` section in the docs, so we can track changes and new feature properly from v0.3 onwards

### CODE REVIEW

**Comment by rabernat** [comment]
Great! Do you envision filling this in for 0.3? You can get a rough idea from looking at the recently merged PRs:
https://github.com/xgcm/xgcm/pulls?q=is%3Apr+is%3Aclosed

**Comment by jbusecke** [comment]
Oh I was thinking just starting from now. But I can try to do that backdated as well. Trying to set up CI for my model setup at the moment 😨. Depending on how that goes I might have some bandwidth later.

**Comment by jbusecke** [comment]
Ok I added all the merged PRs to the document + a little header for the release. 

cc'ing @timothyas @andersy005.

**Comment by timothyas** [comment]
This is a nice addition @jbusecke! Looks good to me.

**Pull request merged**
