### PR TITLE
corrected error testing function

### PR DESCRIPTION
**Pull request by jbusecke**
Changes the checking procedure for error messages (see #133).

### CODE REVIEW

**Comment by jbusecke** [comment]
@rabernat, could you confirm that this error message is deprecated?

```
    with pytest.raises(ValueError) as excinfo:
        ax.interp(ds.data_c, "left", boundary="fill")
    assert (
        excinfo.value.args[0] == "`boundary=fill` is not allowed "
        "with periodic axis X."
    )
```
I could not find this message in the code anywhere.

**Comment by jbusecke** [comment]
closed via #136

**Comment by rabernat** [comment]
Sorry I am reinventing all the bug fixes that you already discovered. 🤷‍♂

**Comment by jbusecke** [comment]
Thats ok. I just have to add that using this PR would have been more “atomic“...muhahaha, jk.

**Pull request closed without merging**
